#*******************************************************************************************#
#*----- Description :   CI for project with flex and  c++                               ****#
#*----- Auteur      :   (c) 2021 Aubertin Emmanuel                                      ****#
#*----- GitHub      :   Athomisos    | GitLab : aTHO_                                   ****#
#*----- LinkedIn    :   linkedin.com/in/emmanuel-aubertin                               ****#
#*******************************************************************************************#

image: gcc # https://hub.docker.com/_/gcc/

build:
  stage: build
  script:
    - apt update && apt -y install make flex
    - make clean
    - make 
  artifacts:
    paths:
      - compilateur

Compilation:
  stage: test
  needs: ["build"]
  script:
    - ./compilateur <input.aTHO >test.s
    - gcc  -ggdb -no-pie -fno-pie test.s -o test.bin
    - ./test.bin
