# see https://hub.docker.com/_/gcc/
image: gcc

build:
  stage: build
  script:
    - apt update && apt -y install make
    - make clean
    - flex++ -d -otokeniser.cpp tokeniser.l
    - g++ -c tokeniser.cpp
    - g++ -ggdb -o compilateur compilateur.cpp tokeniser.o
  artifacts:
    paths:
      - compilateur

test:
  stage: test
  script:
    - ./compilateur <test.p >test.s
    - gcc  -ggdb -no-pie -fno-pie test.s -o test
